---
title: "tsc_vignette"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{tsc_vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(tsclassification)
```

## Working with files on disk

```{r}
# Working with local .arff files:
train_data = file.path(system.file("arff", package="tsclassification"), "GunPoint_TRAIN.arff")
test_data  = file.path(system.file("arff", package="tsclassification"), "GunPoint_TEST.arff")
# We choose DTW1NN
classifName = "DTW1NN"
tsc = TSClassifier$new(classifName)
# Train and predict
tsc$train(train_data)
p = tsc$predict(test_data)
```

## Working with a data.frame

```{r}
# Working with data.frames custom writing to file
library(mlr)
df = getTaskData(gunpoint.task)
target = getTaskTargetNames(gunpoint.task)
data_path = data_to_path(df, target = target)
tsc$train(data_path)
p = tsc$predict(data_path)
```

```{r}
# Working with data.frames, specifying a target
df = getTaskData(gunpoint.task)
target = getTaskTargetNames(gunpoint.task)
tsc = TSClassifier$new(classifName, target = target)
tsc$train(df)
p = tsc$predict(df)
```

## Working with Hyperparameters:

See `?tsc_classifiers` for a list of available hyperparameters for a given method.

```{r}
df = getTaskData(gunpoint.task)
target = getTaskTargetNames(gunpoint.task)
tsc = TSClassifier$new("timeseriesweka.classifiers.BOSS", target = target)
tsc$train(df, par_vals = list(setMaxEnsembleSize = 1))
p = tsc$predict(df)
p
```

```{r}
df = getTaskData(gunpoint.task)
target = getTaskTargetNames(gunpoint.task)
tsc = TSClassifier$new("timeseriesweka.classifiers.TSF", target = target)
tsc$train(df, par_vals = list(setNumTrees = 10))
p = tsc$predict(df)
p
```
